spring:
  application:
    name: zcrud
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10000000
      max-request-size: 10000000

server:
  port: 8082
  servlet:
    context-path: /${spring.application.name}

app:
  database-type: mongo
  static-min-url: ${server.servlet.context-path}/assets
  file-service-base64-upload-api: http://localhost:8085/zfiles/api/object/base64
  key-cloak-logout-url: http://localhost:8080/auth/realms/jayameen/protocol/openid-connect/logout?client_id=zcrud

  mongo:
    collections:
      metadata: collections_metadata
      files: files

---
spring:
  config:
    activate:
      on-profile: default

  data:
    mongodb:
      host: localhost
      port: 27017
      database: zcrud
      authentication-database: admin
      username: root
      password: Omsairam551979

  security:
    oauth2:
      client:
        registration:
          zcrud:
            provider: keycloak
            client-id: zcrud
            client-secret: 1puPsVD0ffzlxaG2r9oChEAnA5UhZvgU
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8082/zcrud/login/authcode"
            scope: openid
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/auth/realms/jayameen/protocol/openid-connect/auth
            token-uri: http://localhost:8080/auth/realms/jayameen/protocol/openid-connect/token
            jwk-set-uri: http://localhost:8080/auth/realms/jayameen/protocol/openid-connect/certs
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/jayameen
          jwk-set-uri: http://localhost:8080/auth/realms/jayameen/protocol/openid-connect/certs
          introspection-uri: http://localhost:8080/auth/realms/jayameen/protocol/openid-connect/token/introspect
        opaquetoken:
          client-id: zcrud
          client-secret: 1puPsVD0ffzlxaG2r9oChEAnA5UhZvgU
          issuer-uri: http://localhost:8080/auth/realms/jayameen
          introspection-uri: http://localhost:8080/auth/realms/jayameen/protocol/openid-connect/token/introspect